name: On PR Merge

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: 1-build-image-docker
        run: echo "Build image Docker"
      - name: 2-login-to-Docker-Registry
        run: echo "login to Docker Registry"
      - name: 3-push-Docker-image
        run: echo "push docker image"

  Deploy-to-Service-DS-Staging:
    runs-on: ubuntu-latest
    steps:
      - name: 1-deploy-to-docker-swarm-staging
        run: echo "deploy..."