name: On PR Merge

on:
  pull_request:
    types: [ closed ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-1
        run: echo "Hello On Merge - 1"
      - name: my-step-2
        run: echo "Hello On Merge - 2"