name: On Pull Request

on: 
  pull_request:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-1
        run: echo "Hello On PR - 1"
      - name: my-step-2
        run: echo "Hello On PR - 2"
