name: On Pull Request

on: 
  pull_request:
    branches: [ main ]

jobs:
  Build-image-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: build-image-docker
        run: echo "Build..."
      - name: Testing-Docker-image
        run: echo "Testing"
