name: On Pull Request

on: 
  pull_request:
    branches: [ main ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build The Docker image
        run: docker build -f Dockerfile -t brdcookies6969/test-git:pr .
