name: On Release

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  Deploy-to-Prod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy-to-Prod
        run: echo "Deploy...."